on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

name: Post CI

# This is adapted from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run (2022-07-17)

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR Data
        uses: dawidd6/action-download-artifact@5004d5476e64af71d021e6c98993829d8820969d
        with:
          name: pr_number
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Data
        id: save-pr-data
        run: |
          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
          echo "pr_sha=$(cat pr_sha)" >> $GITHUB_OUTPUT
          echo "merge_sha=$(cat merge_sha)" >> $GITHUB_OUTPUT

      - name: Add Comment
        uses: marocchino/sticky-pull-request-comment@0170f2ea39a1607b3be8296584b8ab8106e1bb9f
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          recreate: true
          message: |
            The commit ${{ steps.save-pr-data.outputs.pr_sha }} (as a parent of ${{ steps.save-pr-data.outputs.merge_sha }}) contains errors.
            Please inspect the [Run Summary](https://github.com/ethereum/EIPs/pull/${{ steps.save-pr-data.outputs.pr_number }}/files) for details.
